# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Blog-Metadata-Language
version:      0.01
version_from: lib/WWW/Blog/Metadata/Language.pm
installdirs:  site
requires:
    Test::More:                    0
    Text::Language::Guess:         0
    version:                       0
    WWW::Blog::Metadata:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
